frontend/html/popup.css, frontend/html/popup.html, frontend/html/register1.css, frontend/html/register1.html
=> [Feat] 회원가입 페이지 기능 구현

.idea/encodings.xml, .idea/misc.xml, backend/pom.xml, backend/src/main/java/com/HelloRolha/HR/feature/approve/controller/ApproveController.java, backend/src/main/java/com/HelloRolha/HR/feature/approve/model/Approve.java, backend/src/main/java/com/HelloRolha/HR/feature/approve/model/ApproveFile.java, backend/src/main/java/com/HelloRolha/HR/feature/approve/model/ApproveLine.java, backend/src/main/java/com/HelloRolha/HR/feature/approve/model/dto/ApproveCreateRes.java, backend/src/main/java/com/HelloRolha/HR/feature/approve/model/dto/ApproveList.java, backend/src/main/java/com/HelloRolha/HR/feature/approve/model/dto/ApproveListRes.java, backend/src/main/java/com/HelloRolha/HR/feature/approve/model/dto/ApproveReadRes.java, backend/src/main/java/com/HelloRolha/HR/feature/approve/model/dto/ApproveUpdate.java, backend/src/main/java/com/HelloRolha/HR/feature/approve/model/dto/ApproveUpdateRes.java, backend/src/main/java/com/HelloRolha/HR/feature/approve/repo/ApproveFileRepository.java, backend/src/main/java/com/HelloRolha/HR/feature/approve/service/ApproveService.java, backend/src/main/java/com/HelloRolha/HR/feature/commute/controller/CommuteController.java
BaseEntity를 상속받아서 코드를 작성하는 도중 에러가 지속적으로 발생하므로 원상복구시키고 현재 기본 crud만 작성
Fixes: #13
=> [Feat] Approve 결재만들기 기능 구현(#13)

.idea/be02-fin-Hello_R_loha-HRsystem.iml, backend/src/main/java/com/HelloRolha/HR/feature/commute/controller/CommuteController.java, backend/src/main/java/com/HelloRolha/HR/feature/commute/model/Commute.java, backend/src/main/java/com/HelloRolha/HR/feature/commute/model/dto/CommuteDto.java, backend/src/main/java/com/HelloRolha/HR/feature/commute/service/CommuteService.java
commute 퇴근 기능을 출근 시간이 생성된 후 나타나게하고 총 업무 시간을 계산하여 db에 같이 저장되도록 하였다.
=> [Fix] commute 퇴근 기능 수정(#35)

frontend/html/popup.css, frontend/html/popup.html, frontend/html/register1.css, frontend/html/register1.html
피그마 형식에 따라 회원가입 팝업 페이지 기능을 추가했다
=> [Feat] 회원가입 팝업  페이지 기능 구현( #48)

backend/src/main/java/com/HelloRolha/HR/common/entity/ApproveLineBaseEntity.java, backend/src/main/java/com/HelloRolha/HR/feature/goout/repo/GooutRepository.java
=> [Refactor] 커밋 복구

frontend/html/HRgoout.html
피그마 양식에 따라 인사담당자가가 휴가를 승인하는 기능을 추가
=> [feat] 인사담당자 휴가 승인페이지 구현( #55)

backend/src/main/java/com/HelloRolha/HR/feature/goout/model/Goout.java, backend/src/main/java/com/HelloRolha/HR/feature/goout/model/GooutType.java, backend/src/main/java/com/HelloRolha/HR/feature/goout/model/dto/GooutCreateReq.java, backend/src/main/java/com/HelloRolha/HR/feature/goout/model/dto/GooutList.java, backend/src/main/java/com/HelloRolha/HR/feature/goout/model/dto/GooutRead.java, backend/src/main/java/com/HelloRolha/HR/feature/goout/model/dto/GooutUpdateReq.java, backend/src/main/java/com/HelloRolha/HR/feature/goout/service/GooutService.java
각자 작동하던 휴가타입, 휴가결재라인, 휴가를 연동하였음
=> [Feat] 휴가타입, 휴가결재라인, 휴가 연동

backend/src/main/java/com/HelloRolha/HR/feature/board/controller/BoardController.java, backend/src/main/java/com/HelloRolha/HR/feature/board/model/Board.java, backend/src/main/java/com/HelloRolha/HR/feature/board/model/dto/BoardDto.java, backend/src/main/java/com/HelloRolha/HR/feature/board/repository/BoardRepository.java, backend/src/main/java/com/HelloRolha/HR/feature/board/service/BoardNotFoundException.java, backend/src/main/java/com/HelloRolha/HR/feature/board/service/BoardService.java
프론트 메인 화면에 들어갈 공지 사항의 페이지를 구현하였습니다. 현재 기능에서 파일 추가 기능 구현 필요
=> [Feat] 공지사항 기능 구현 (#112)

backend/src/main/java/com/HelloRolha/HR/common/entity/ApproveLineBaseEntity.java, backend/src/main/java/com/HelloRolha/HR/error/ApproveNotFoundException.java, backend/src/main/java/com/HelloRolha/HR/feature/approve/controller/ApproveController.java, backend/src/main/java/com/HelloRolha/HR/feature/approve/controller/ApproveLineController.java, backend/src/main/java/com/HelloRolha/HR/feature/approve/model/Approve.java, backend/src/main/java/com/HelloRolha/HR/feature/approve/model/ApproveFile.java, backend/src/main/java/com/HelloRolha/HR/feature/approve/model/ApproveLine.java, backend/src/main/java/com/HelloRolha/HR/feature/approve/model/dto/ApproveCreateReq.java, backend/src/main/java/com/HelloRolha/HR/feature/approve/model/dto/ApproveLine/ApproveLineCreateReq.java, backend/src/main/java/com/HelloRolha/HR/feature/approve/model/dto/ApproveLine/ApproveLinePatchReq.java, backend/src/main/java/com/HelloRolha/HR/feature/approve/repo/ApproveFileRepository.java, backend/src/main/java/com/HelloRolha/HR/feature/approve/repo/ApproveLineRepository.java, backend/src/main/java/com/HelloRolha/HR/feature/approve/service/ApproveLineService.java, backend/src/main/java/com/HelloRolha/HR/feature/approve/service/ApproveService.java, backend/src/main/java/com/HelloRolha/HR/feature/employee/model/entity/Employee.java
=> [Refactor] approve 기능의 코드 정리

backend/src/main/java/com/HelloRolha/HR/feature/approve/controller/ApproveController.java, backend/src/main/java/com/HelloRolha/HR/feature/approve/controller/ApproveLineController.java, backend/src/main/java/com/HelloRolha/HR/feature/approve/model/Approve.java, backend/src/main/java/com/HelloRolha/HR/feature/approve/model/ApproveFile.java, backend/src/main/java/com/HelloRolha/HR/feature/approve/model/ApproveLine.java, backend/src/main/java/com/HelloRolha/HR/feature/approve/model/dto/Approve/ApproveCreateReq.java, backend/src/main/java/com/HelloRolha/HR/feature/approve/model/dto/Approve/ApproveCreateRes.java, backend/src/main/java/com/HelloRolha/HR/feature/approve/model/dto/Approve/ApproveList.java, backend/src/main/java/com/HelloRolha/HR/feature/approve/model/dto/Approve/ApproveListRes.java, backend/src/main/java/com/HelloRolha/HR/feature/approve/model/dto/Approve/ApproveRead.java, backend/src/main/java/com/HelloRolha/HR/feature/approve/model/dto/Approve/ApproveReturn.java, backend/src/main/java/com/HelloRolha/HR/feature/approve/model/dto/Approve/ApproveUpdate.java, backend/src/main/java/com/HelloRolha/HR/feature/approve/model/dto/Approve/ApproveUpdateRes.java, backend/src/main/java/com/HelloRolha/HR/feature/approve/model/dto/ApproveLine/ApproveLineConfirm.java, backend/src/main/java/com/HelloRolha/HR/feature/approve/model/dto/ApproveLine/ApproveLineList.java, backend/src/main/java/com/HelloRolha/HR/feature/approve/model/dto/ApproveLine/ApproveLineRead.java, backend/src/main/java/com/HelloRolha/HR/feature/approve/repo/ApproveFileRepository.java, backend/src/main/java/com/HelloRolha/HR/feature/approve/service/ApproveLineService.java, backend/src/main/java/com/HelloRolha/HR/feature/approve/service/ApproveService.java
결재Line을 설정하여 결재를 만들고 수정할 수 있도록 수정
Fixes: #13
=> [Feat] Approve CRUD 추가(#13, #14, #16, #17, #18, #19, #20)

frontend/.env, frontend/public/styles.css, frontend/src/App.vue, frontend/src/components/HeaderComponent.vue, frontend/src/components/SideBar.vue, frontend/src/main.js, frontend/src/pages/LoginPage.vue, frontend/src/pages/MainPage.vue, frontend/src/pages/SignUpPage.vue, frontend/src/router/index.js
- 로그인 페이지와 회원가입 페이지가 작동되도록 만들었다
- VUE 프로젝트로 만들었다
Close: #48, #49
=> [Feat] 로그인 및 회원가입 페이지 완성 (#48 #49)

backend/src/main/java/com/HelloRolha/HR/feature/board/controller/BoardController.java, backend/src/main/java/com/HelloRolha/HR/feature/board/model/Board.java, backend/src/main/java/com/HelloRolha/HR/feature/board/model/BoardFile.java, backend/src/main/java/com/HelloRolha/HR/feature/board/model/dto/BoardDto.java, backend/src/main/java/com/HelloRolha/HR/feature/board/repository/BoardFileRepository.java, backend/src/main/java/com/HelloRolha/HR/feature/board/service/BoardService.java
공지 사항을 생성할 때 필요한 기능 중 파일 추가 기능을 추가하여 구현하였습니다.
=> [Fix] 공지 사항 게시글 기능 추가 (#112)

frontend/html/main.css, frontend/html/main.html, frontend/html/main2.html
=> [feat] 메인페이지 달력, 출근기능, 공지사항, 결재사항 추가 (#46)

frontend/package-lock.json, frontend/package.json, frontend/src/components/SideBar.vue, frontend/src/pages/OvertimeCreatePage.vue, frontend/src/router/index.js
-초과 근무 프론트를 html에서 vue로 변경하였습니다.
=> [Feat] 프론트 초과근무 vue 기능 구현 (#126)

backend/src/main/java/com/HelloRolha/HR/feature/commute/controller/CommuteController.java, backend/src/main/java/com/HelloRolha/HR/feature/commute/service/CommuteService.java
- mainPage 페이지 생성을 위해 오늘 출근했는지 확인하는 기능 구현
=> [Feat] 출퇴근 확인 기능

backend/src/main/java/com/HelloRolha/HR/feature/commute/service/CommuteService.java, backend/src/main/java/com/HelloRolha/HR/feature/employee/model/dto/EmployeeSalaryDto.java, backend/src/main/java/com/HelloRolha/HR/feature/employee/model/entity/Employee.java, backend/src/main/java/com/HelloRolha/HR/feature/employee/service/EmployeeService.java, backend/src/main/java/com/HelloRolha/HR/feature/goout/repo/GooutRepository.java, backend/src/main/java/com/HelloRolha/HR/feature/goout/service/GooutService.java, backend/src/main/java/com/HelloRolha/HR/feature/manager/controller/ManagerController.java, backend/src/main/java/com/HelloRolha/HR/feature/overtime/repository/OvertimeRepository.java, backend/src/main/java/com/HelloRolha/HR/feature/overtime/service/OvertimeService.java, backend/src/main/java/com/HelloRolha/HR/feature/salary/model/dto/SalaryDto.java, backend/src/main/java/com/HelloRolha/HR/feature/salary/service/SalaryService.java
- 배치 처리에 사용할 기능으로 전 직원의 휴가, 초과근무, 출근일을 반영하여 급여를 보여준다
=> [Feat] 급여 계산 기능 생성

frontend/src/pages/Approve/ApproveCreatePage.vue
Frontend에서 결재 등록 기능을 추가하고 등록 후 list페이지로 넘어가게 기능을 추가
Fixes: #52
=> [Feat] Approve Create기능 추ê (#52)

frontend/src/components/SideBar.vue, frontend/src/pages/Approve/ApproveListPage.vue, frontend/src/pages/Approve/ApproveReadPage.vue, frontend/src/router/index.js
결재 상세페이지 기능을 추가하였고, db에 저장된 정보를 받아오는
기능추가예정
Fixes: #53, #67
=> [Feat] Approve Read 기능 추가(#53, #67)

backend/src/main/java/com/HelloRolha/HR/feature/overtime/controller/OvertimeController.java, backend/src/main/java/com/HelloRolha/HR/feature/overtime/model/Overtime.java, backend/src/main/java/com/HelloRolha/HR/feature/overtime/model/dto/OvertimeDto.java, backend/src/main/java/com/HelloRolha/HR/feature/overtime/service/OvertimeService.java
- 기본적인 초과 근무 crud와 인사 담당자만 초과 근무를 승인할 수 있도록 하였습니다.
=> [Fix] 초과 근무 권한 부여 기능 구현 (#32, #8, #91, #126)

backend/src/main/java/com/HelloRolha/HR/feature/salary/model/entity/Salary.java
=> [Feat] Salary Entity 생성

backend/src/main/java/com/HelloRolha/HR/feature/overtime/model/Overtime.java, backend/src/main/java/com/HelloRolha/HR/feature/overtime/service/OvertimeService.java
=> [Fix] merge 과정에서 날아간 코드 복구

frontend/src/components/goout/GooutCreate.vue, frontend/src/components/goout/GooutRead.vue, frontend/src/components/goout/GooutUpdate.vue
-GooutCreate 완성
-GooutRead 완성
-GooutUpdate 완성
Close: #56, #115
=> [Feat] 휴가 프론트 완성 (#56, #115)

frontend/src/App.vue, frontend/src/components/HeaderComponent.vue, frontend/src/components/SideBar.vue, frontend/src/pages/goout/GooutPage.vue, frontend/src/pages/goout/GooutTypePage.vue
-휴가에 헤더, 사이드바 추가하였음
-사이드바에 휴가, 출퇴근 연결하였음
=> [Fix] 헤더, 사이드바 보수작업

backend/src/main/java/com/HelloRolha/HR/feature/approve/controller/ApproveController.java, backend/src/main/java/com/HelloRolha/HR/feature/approve/controller/ApproveLineController.java, backend/src/main/java/com/HelloRolha/HR/feature/approve/model/Approve.java, backend/src/main/java/com/HelloRolha/HR/feature/approve/model/ApproveLine.java, backend/src/main/java/com/HelloRolha/HR/feature/approve/model/dto/Approve/ApproveCreateReq.java, backend/src/main/java/com/HelloRolha/HR/feature/approve/model/dto/Approve/ApproveCreateRes.java, backend/src/main/java/com/HelloRolha/HR/feature/approve/model/dto/Approve/ApproveRead.java, backend/src/main/java/com/HelloRolha/HR/feature/approve/model/dto/Approve/ApproveUpdate.java, backend/src/main/java/com/HelloRolha/HR/feature/approve/model/dto/Approve/ApproveUpdateRes.java, backend/src/main/java/com/HelloRolha/HR/feature/approve/model/dto/ApproveLine/ApproveConfirmRes.java, backend/src/main/java/com/HelloRolha/HR/feature/approve/model/dto/ApproveLine/ApproveLineRead.java, backend/src/main/java/com/HelloRolha/HR/feature/approve/model/dto/ApproveLine/ApproveLineUpdateReq.java, backend/src/main/java/com/HelloRolha/HR/feature/approve/model/dto/ApproveLine/ReturnStatusRes.java, backend/src/main/java/com/HelloRolha/HR/feature/approve/repo/ApproveLineRepository.java, backend/src/main/java/com/HelloRolha/HR/feature/approve/service/ApproveLineService.java, backend/src/main/java/com/HelloRolha/HR/feature/approve/service/ApproveService.java
approve 반려 및 회수 기능 추가 및 결제 목록페이지, 결제 상세페이지 코드 수정
close: #16, #22
approve 반려 기능 추가
approve 회수 기능 추가
approve 상세 조회 중 confirmer 이름 나오게 수정
approve 목록페이지 상태 및 confirmer 이름 나오게 수정
=> [Feat] Approve 기능 추가 및 코드 수정(#16 #22)

frontend/src/pages/Approve/ApproveCreatePage.vue, frontend/src/pages/Approve/ApproveListPage.vue, frontend/src/pages/Approve/ApproveReadPage.vue, frontend/src/pages/Approve/ApproveUpdatePage.vue
Approve 화면 구현 완료
close: #51, #52, #53
approve 수정 화면 구현 및 frontend 코드 구조 수정
=> [Feat] Approve 화면 구현(#51 #52 #53)

backend/src/main/java/com/HelloRolha/HR/feature/approve/model/Approve.java, backend/src/main/java/com/HelloRolha/HR/feature/approve/model/dto/ApproveLine/ApproveLineRead.java, backend/src/main/java/com/HelloRolha/HR/feature/approve/service/ApproveLineService.java, backend/src/main/java/com/HelloRolha/HR/feature/approve/service/ApproveService.java
=> [Feat] Approve 코드 수정

backend/src/main/java/com/HelloRolha/HR/feature/goout/model/dto/GooutRead.java, backend/src/main/java/com/HelloRolha/HR/feature/goout/service/GooutService.java
-프론트에서 update페이지에 들어가면 read페이지의 정보를 그대로 받아오기 위해 read에서 외래키의 id도 출력하도록 변경하였음
=> [Fix] GooutRead 수정

backend/src/main/java/com/HelloRolha/HR/feature/approve/controller/ApproveController.java, backend/src/main/java/com/HelloRolha/HR/feature/approve/model/dto/Approve/ApproveRead.java, backend/src/main/java/com/HelloRolha/HR/feature/approve/model/dto/Approve/ApproveReturn.java, backend/src/main/java/com/HelloRolha/HR/feature/approve/model/dto/Approve/ApproveUpdate.java, backend/src/main/java/com/HelloRolha/HR/feature/approve/service/ApproveService.java
=> [Feat] Approve 파일 기능 추가

cdtest.txt
=> [Docs] ci test

backend/src/main/java/com/HelloRolha/HR/feature/goout/controller/GooutLineController.java, backend/src/main/java/com/HelloRolha/HR/feature/goout/model/Goout.java, backend/src/main/java/com/HelloRolha/HR/feature/goout/model/GooutLine.java, backend/src/main/java/com/HelloRolha/HR/feature/goout/model/dto/GooutCreateReq.java, backend/src/main/java/com/HelloRolha/HR/feature/goout/model/dto/GooutLineConfirm.java, backend/src/main/java/com/HelloRolha/HR/feature/goout/model/dto/GooutLineCreateReq.java, backend/src/main/java/com/HelloRolha/HR/feature/goout/model/dto/GooutLineList.java, backend/src/main/java/com/HelloRolha/HR/feature/goout/model/dto/GooutLineRead.java, backend/src/main/java/com/HelloRolha/HR/feature/goout/model/dto/GooutLineUpdateReq.java, backend/src/main/java/com/HelloRolha/HR/feature/goout/model/dto/GooutList.java, backend/src/main/java/com/HelloRolha/HR/feature/goout/model/dto/GooutRead.java, backend/src/main/java/com/HelloRolha/HR/feature/goout/model/dto/GooutUpdateReq.java, backend/src/main/java/com/HelloRolha/HR/feature/goout/repo/GooutLineRepository.java, backend/src/main/java/com/HelloRolha/HR/feature/goout/service/GooutLineService.java, backend/src/main/java/com/HelloRolha/HR/feature/goout/service/GooutService.java
=> [Fix] ApproveLineBaseEntity 사용하도록 전체적인 코드수정

backend/src/main/java/com/HelloRolha/HR/config/SecurityConfig.java, backend/src/main/java/com/HelloRolha/HR/feature/employee/controller/EmployeeController.java, backend/src/main/java/com/HelloRolha/HR/feature/employee/repo/EmployeeRepository.java, backend/src/main/java/com/HelloRolha/HR/feature/employee/service/EmployeeService.java, backend/src/main/java/com/HelloRolha/HR/feature/manager/controller/ManagerController.java
- 회원가입 승인할 사람이 없을 때를 위한 매소드 추가
=> [feat] manager 사용자 생성 코드 작성

frontend/src/components/goout/GooutRead.vue
=> [Feat] 첨부파일 다운로드 되도록 변경

backend/src/main/java/com/HelloRolha/HR/feature/goout/controller/GooutController.java, backend/src/main/java/com/HelloRolha/HR/feature/goout/model/GooutFile.java, backend/src/main/java/com/HelloRolha/HR/feature/goout/model/dto/GooutFileDto.java, backend/src/main/java/com/HelloRolha/HR/feature/goout/repo/GooutFileRepository.java, backend/src/main/java/com/HelloRolha/HR/feature/goout/service/GooutService.java
-그림파일만 볼 수 있고, 문서파일 등 관련해선 미완성 단계
=> [Feat] Read페이지 첨부파일관련 추가

frontend/nginx/default.conf, frontend/src/components/goout/GooutRead.vue
- 휴가 상세 페이지 파일에 backend 변수가 2개 있었음.
=> [Fix] 오류 해결

backend/src/main/java/com/HelloRolha/HR/feature/goout/controller/GooutController.java, backend/src/main/java/com/HelloRolha/HR/feature/goout/model/dto/GooutCreateReq.java, backend/src/main/java/com/HelloRolha/HR/feature/goout/model/dto/GooutCreateRes.java, backend/src/main/java/com/HelloRolha/HR/feature/goout/service/GooutLineService.java, backend/src/main/java/com/HelloRolha/HR/feature/goout/service/GooutService.java
=> [Refactor] 리팩토링

frontend/src/pages/Approve/ApproveCreatePage.vue, frontend/src/pages/Approve/ApproveListPage.vue, frontend/src/pages/Approve/ApproveReadPage.vue
=> [Fix] Approve 코드 구조 변경

frontend/src/components/goout/GooutRead.vue, frontend/test-results/report.xml, frontend/tests/unit/boardlist.spec.js, frontend/tests/unit/login.spec.js
프론트엔드 로그인, 공지사항 리스트 페이지 testcode를 추가
=> [feat] 로그인, 공지사항 리스트 testcode 추가 ( #160)

frontend/src/components/goout/GooutRead.vue, frontend/src/pages/ManagerPage.vue, frontend/src/pages/Salary/SalaryListPage.vue, frontend/src/router/index.js
=> [Feat] 관리자 월급 조회 페이지 구현

backend/pom.xml, backend/src/main/java/com/HelloRolha/HR/feature/employee/model/entity/Employee.java, backend/src/main/java/com/HelloRolha/HR/feature/employee/service/EmployeeService.java, backend/src/main/java/com/HelloRolha/HR/feature/manager/controller/ManagerController.java, backend/src/main/java/com/HelloRolha/HR/feature/overtime/service/OvertimeService.java, backend/src/main/java/com/HelloRolha/HR/feature/salary/model/dto/getSalaryListRes.java, backend/src/main/java/com/HelloRolha/HR/feature/salary/model/entity/Salary.java, backend/src/main/java/com/HelloRolha/HR/feature/salary/repo/SalaryRepository.java, backend/src/main/java/com/HelloRolha/HR/feature/salary/repo/SalaryRepositoryCustom.java, backend/src/main/java/com/HelloRolha/HR/feature/salary/repo/SalaryRepositoryCustomImpl.java, backend/src/main/java/com/HelloRolha/HR/feature/salary/service/SalaryService.java
=> 급여 조회 기능 구현

backend/src/main/java/com/HelloRolha/HR/feature/board/repository/BoardFileRepository.java, backend/src/main/java/com/HelloRolha/HR/feature/board/repository/BoardRepository.java, backend/src/main/java/com/HelloRolha/HR/feature/board/repository/BoardRepositoryCustom.java, backend/src/main/java/com/HelloRolha/HR/feature/board/repository/BoardRepositoryCustomImpl.java, backend/src/main/java/com/HelloRolha/HR/feature/board/service/BoardService.java
=> [Feat] 공지사항 쿼리 dsl 및 n+1 해결 (#218)

backend/pom.xml, backend/src/main/java/com/HelloRolha/HR/feature/approve/controller/ApproveController.java, backend/src/main/java/com/HelloRolha/HR/feature/approve/controller/ApproveLineController.java, backend/src/main/java/com/HelloRolha/HR/feature/approve/model/dto/approve/ApproveCreateReq.java, backend/src/main/java/com/HelloRolha/HR/feature/approve/model/dto/approve/ApproveCreateRes.java, backend/src/main/java/com/HelloRolha/HR/feature/approve/model/dto/approve/ApproveList.java, backend/src/main/java/com/HelloRolha/HR/feature/approve/model/dto/approve/ApproveRead.java, backend/src/main/java/com/HelloRolha/HR/feature/approve/model/dto/approve/ApproveReturn.java, backend/src/main/java/com/HelloRolha/HR/feature/approve/model/dto/approve/ApproveUpdate.java, backend/src/main/java/com/HelloRolha/HR/feature/approve/model/dto/approveFile/ApproveFileDto.java, backend/src/main/java/com/HelloRolha/HR/feature/approve/model/dto/approveLine/ApproveConfirmRes.java, backend/src/main/java/com/HelloRolha/HR/feature/approve/model/dto/approveLine/ApproveLineConfirm.java, backend/src/main/java/com/HelloRolha/HR/feature/approve/model/dto/approveLine/ApproveLineCreateReq.java, backend/src/main/java/com/HelloRolha/HR/feature/approve/model/dto/approveLine/ApproveLineList.java, backend/src/main/java/com/HelloRolha/HR/feature/approve/model/dto/approveLine/ApproveLineRead.java, backend/src/main/java/com/HelloRolha/HR/feature/approve/model/dto/approveLine/ApproveLineUpdateReq.java, backend/src/main/java/com/HelloRolha/HR/feature/approve/model/dto/approveLine/ReturnStatusRes.java, backend/src/main/java/com/HelloRolha/HR/feature/approve/repo/ApproveFileRepository.java, backend/src/main/java/com/HelloRolha/HR/feature/approve/repo/ApproveRepository.java, backend/src/main/java/com/HelloRolha/HR/feature/approve/repo/ApproveRepositoryCustomImpl.java, backend/src/main/java/com/HelloRolha/HR/feature/approve/service/ApproveLineService.java, backend/src/main/java/com/HelloRolha/HR/feature/approve/service/ApproveService.java
- ApproveRead 회수 기능 및 파일 다운로드 기능 추가, delete 대신 cancel사용하도록 코드 수정,
- 패키지 이름 변경으로 인한 전체적인 코드 수정
=> [Feat] Approve 회수 기능 및 파일 다운로드 기능 추가

frontend/src/pages/Approve/ApproveCreatePage.vue, frontend/src/pages/Approve/ApproveListPage.vue, frontend/src/pages/Approve/ApproveReadPage.vue
- ApproveReadPage 회수 기능 추가 및 파일 다운로드 기능 추가
- 특정 상황일 때 반려 사유가 보이도록 코드 수정
- 전체적인 코드 구조 수정
=> [Feat] Approve 반려 사유 및 파일 다운로드 기능 추가

frontend/src/pages/ManagerPage.vue, frontend/src/pages/Salary/SalaryListPage.vue
- 사용자가 드랍다운을 통해 해당 월의 월급들을 조회할 수 있도록 만들고 있음
=> [Feat] 월급 조회 페이지 검색 기능 구현 중

backend/src/main/java/com/HelloRolha/HR/config/utils/filter/JwtFilter.java, backend/src/main/java/com/HelloRolha/HR/feature/employee/model/entity/Employee.java, backend/src/main/java/com/HelloRolha/HR/feature/employee/repo/EmployeeRepository.java, backend/src/main/java/com/HelloRolha/HR/feature/employee/repo/EmployeeRepositoryCustom.java, backend/src/main/java/com/HelloRolha/HR/feature/employee/repo/EmployeeRepositoryCustomImpl.java, backend/src/main/java/com/HelloRolha/HR/feature/employee/service/EmployeeService.java, backend/src/main/java/com/HelloRolha/HR/feature/manager/controller/ManagerController.java, backend/src/main/java/com/HelloRolha/HR/feature/salary/model/dto/GetDatesOfSalaryRes.java, backend/src/main/java/com/HelloRolha/HR/feature/salary/model/dto/GetSalaryListRes.java, backend/src/main/java/com/HelloRolha/HR/feature/salary/repo/SalaryRepositoryCustom.java, backend/src/main/java/com/HelloRolha/HR/feature/salary/repo/SalaryRepositoryCustomImpl.java, backend/src/main/java/com/HelloRolha/HR/feature/salary/service/SalaryService.java
- 직원에 쿼리dsl 적용 후 월급 계산 할 때도 N+1 문제없도록 만들었음
=> [Refactor] 쿼리문 리펙토링

frontend/src/components/goout/GooutCreate.vue, frontend/src/components/goout/GooutList.vue
- List 역순정렬 (게시글id 높은순으로)
- 백엔드 에러코드 프론트에서 출력
=> [Feat] List 역순으로 정렬 및 예외처리 메시지 출력

backend/src/main/java/com/HelloRolha/HR/feature/goout/controller/GooutController.java, backend/src/main/java/com/HelloRolha/HR/feature/goout/model/dto/GooutListRes.java, backend/src/main/java/com/HelloRolha/HR/feature/goout/repo/GooutRepositoryCustomImpl.java, backend/src/main/java/com/HelloRolha/HR/feature/goout/service/GooutService.java
- BusinessException활용 예외처리
- 레포커스텀임플에서 list역순으로 변경
=> [Feat] list메소드 역순으로 변경, 예외처리

backend/src/main/java/com/HelloRolha/HR/feature/employee/service/EmployeeService.java, backend/src/main/resources/application.yml
=> [Fix] 권한 이름 수정

frontend/src/pages/Approve/ApproveCreatePage.vue, frontend/src/pages/Approve/ApproveListPage.vue, frontend/src/pages/Approve/ApproveReadPage.vue
- 예외처리 화면 출력 
- List 역순 기능
- textarea 일반 글자에서 placeholder로 변경
=> [Feat] 예외처리 화면 출력 및 List 역순 기능 추가

backend/src/main/java/com/HelloRolha/HR/feature/approve/service/ApproveService.java
- 예외처리 기능 추가
- List id역순으로나오게 기능 추가
=> [Feat] 예외처리 추가 및 List 역순서 기능 추가

frontend/src/components/goout/GooutCreate.vue, frontend/src/components/goout/GooutList.vue, frontend/src/components/goout/GooutRead.vue, frontend/src/components/goout/GooutUpdate.vue
=> Frontend/deploy에 Merge안된 goout기능 추가

backend/src/main/java/com/HelloRolha/HR/config/SecurityConfig.java, backend/src/main/java/com/HelloRolha/HR/config/utils/filter/JwtFilter.java, backend/src/main/java/com/HelloRolha/HR/error/ErrorCode.java, backend/src/main/java/com/HelloRolha/HR/feature/overtime/controller/OvertimeController.java, backend/src/main/java/com/HelloRolha/HR/feature/overtime/repository/OvertimeRepositoryCustom.java, backend/src/main/java/com/HelloRolha/HR/feature/overtime/repository/OvertimeRepositoryCustomImpl.java, backend/src/main/java/com/HelloRolha/HR/feature/overtime/service/OvertimeService.java
- 일반 사용자는 다른 사람의 초과근무 내역을 볼 수 있으면 안된다.
=> [Feat] 자신의 초과근무만 볼 수 있도록 하는 기능

frontend/src/pages/Approve/ApproveListPage.vue
=> [Feat] List에서 Page로 변경으로 인한 코드 수정

backend/src/main/java/com/HelloRolha/HR/feature/approve/controller/ApproveController.java, backend/src/main/java/com/HelloRolha/HR/feature/approve/repo/ApproveRepository.java, backend/src/main/java/com/HelloRolha/HR/feature/approve/service/ApproveService.java
- List에서 Page로 변경으로 인한 코드 수정 및 리스트 역순 기능 수정
=> [Feat] List에서 Page로 변경

backend/src/main/java/com/HelloRolha/HR/error/ErrorCode.java, backend/src/main/java/com/HelloRolha/HR/feature/employee/repo/EmployeeRepositoryCustom.java, backend/src/main/java/com/HelloRolha/HR/feature/employee/repo/EmployeeRepositoryCustomImpl.java, backend/src/main/java/com/HelloRolha/HR/feature/employee/service/EmployeeService.java, backend/src/main/java/com/HelloRolha/HR/feature/salary/repo/SalaryRepositoryCustomImpl.java, backend/src/main/java/com/HelloRolha/HR/feature/salary/service/SalaryService.java, backend/src/main/resources/application.yml
- one to many의 관계 여러개¸¦ 조인할 수 없었던 문제였습니다.
=> [Fix] Employee list Query 문이 작동 안하는 문제 해결

backend/pom.xml, backend/src/main/java/com/HelloRolha/HR/config/SecurityConfig.java, backend/src/main/java/com/HelloRolha/HR/config/utils/JwtUtils.java, backend/src/main/java/com/HelloRolha/HR/config/utils/filter/JwtFilter.java, backend/src/main/java/com/HelloRolha/HR/error/security/CustomAccessDeniedHandler.java, backend/src/main/java/com/HelloRolha/HR/error/security/CustomAuthenticationEntryPoint.java, backend/src/main/java/com/HelloRolha/HR/feature/employee/service/EmployeeService.java, backend/src/main/java/com/HelloRolha/HR/feature/manager/controller/ManagerController.java
- 권한 확인하는 부분이 겹쳐서 수정함. 예외처리 추가. 권한확인 용 매소드 추가
=> [Refactor] 토큰 인증 관련 코드와 예외처리 수정

backend/src/main/java/com/HelloRolha/HR/feature/department/controller/DepartmentController.java, backend/src/main/java/com/HelloRolha/HR/feature/employee/controller/EmployeeController.java, backend/src/main/java/com/HelloRolha/HR/feature/employee/repo/EmployeeRepository.java, backend/src/main/java/com/HelloRolha/HR/feature/employee/service/EmployeeService.java
- 직원이 많아지면 일반적인 Dropdown으로 직원을 찾아서 선택하기 힘들기 때문에 부서Id를 통해 직원을 찾아서 선택하도록 코드 추가
=> [Feat] 결재자 선택 방식 변경으로 인한 코드 추가

backend/pom.xml, backend/src/main/java/com/HelloRolha/HR/config/RedisConfig.java, backend/src/main/resources/application.yml
- 개발하다가 방향이 틀어져서 CommuteService 롤백하고 push했음
- 구글링해서 개발하던 차에 강의 자료실에 Redis관련 올려주셔서 오늘 push한 것들 다 reset 할 수도 있음
=> [Feat] Redis 도입 (EmployeeService.getWorkingEmployListForCalculateSalary 때문에 테스트코드 실패)

backend/src/main/java/com/HelloRolha/HR/feature/employee/model/dto/EmployeeDto.java, backend/src/main/java/com/HelloRolha/HR/feature/employee/service/EmployeeService.java
- 결재자 선택 방식 변경으로 인한 코드 추가 (이름 옆에 username 나오도록)
=> [Feat] 결재자 선택 구조 변경으로 인한 코드 변경

backend/src/main/java/com/HelloRolha/HR/config/SecurityConfig.java, backend/src/main/java/com/HelloRolha/HR/feature/commute/controller/CommuteController.java, backend/src/main/java/com/HelloRolha/HR/feature/commute/repository/CommuteRepository.java, backend/src/main/java/com/HelloRolha/HR/feature/commute/service/CommuteService.java, backend/src/main/resources/application.yml
- commute쪽에는 적용됐으나 employee를 불러오는 과정에서 db에 접근하기 때문에 수정 필요
- yml에 redis-host의 ip는 추후 수정 필요 (제 가상머신임)
=> [Feat] Commute redis 적용

frontend/.env, frontend/html/commute.html, frontend/html/main.html, frontend/html/초과근무 만들기.html, frontend/src/components/HeaderComponent.vue, frontend/src/components/goout/GooutCreate.vue, frontend/src/components/goout/GooutRead.vue, frontend/src/components/goout/GooutUpdate.vue, frontend/src/components/goout/gooutType/GooutTypeCreate.vue, frontend/src/components/goout/gooutType/GooutTypeList.vue, frontend/src/components/goout/gooutType/GooutTypeRead.vue, frontend/src/components/goout/gooutType/GooutTypeUpdate.vue, frontend/src/pages/Approve/ApproveCreatePage.vue, frontend/src/pages/Approve/ApproveListPage.vue, frontend/src/pages/Approve/ApproveReadPage.vue, frontend/src/pages/Approve/ApproveUpdatePage.vue, frontend/src/pages/BoardCreatePage.vue, frontend/src/pages/BoardListPage.vue, frontend/src/pages/BoardReadPage.vue, frontend/src/pages/BoardUpdatePage.vue, frontend/src/pages/LoginPage.vue, frontend/src/pages/MainPage.vue, frontend/src/pages/ManagerPage.vue, frontend/src/pages/OvertimeApproveaPage.vue, frontend/src/pages/OvertimeCreatePage.vue, frontend/src/pages/OvertimeDetailPage.vue, frontend/src/pages/OvertimeListPage.vue, frontend/src/pages/OvertimeModifyPage.vue, frontend/src/pages/Salary/SalaryListPage.vue, frontend/src/pages/SignUpPage.vue
- develop에서 개발해버려서 임시로 브랜치 만들었습니다 지울게요 지송
- localhost:8080 조심
- 메인페이지 퇴근이후엔 새로고침해야 시간이 보임
- 메인페이지 시간출력 이상하긴함
=> [Fix] 오류해결 (메인페이지 공지사항, 출퇴근)

backend/src/main/java/com/HelloRolha/HR/feature/commute/service/CommuteService.java
=> [Feat] redis 만료기간 지정

frontend/src/components/goout/GooutCreate.vue
=> [Fix] 버튼에 메소드 적용

frontend/src/components/goout/GooutCreate.vue, frontend/src/components/goout/GooutList.vue, frontend/src/pages/Approve/ApproveListPage.vue
- style 수정으로 인한 코드 변경 및 코드 구조 변경
=> [Design] Approve 및 Goout List 페이지 style 수정

frontend/src/pages/Approve/ApproveListPage.vue
=> [Style] approveList 스타일 변경

backend/src/main/java/com/HelloRolha/HR/config/SecurityConfig.java, backend/src/main/java/com/HelloRolha/HR/config/utils/JwtUtils.java, backend/src/main/java/com/HelloRolha/HR/config/utils/filter/JwtFilter.java, backend/src/main/java/com/HelloRolha/HR/error/TokenNotFoundException.java, backend/src/main/java/com/HelloRolha/HR/error/TokenRefreshException.java, backend/src/main/java/com/HelloRolha/HR/feature/employee/model/dto/Login/LoginRes.java, backend/src/main/java/com/HelloRolha/HR/feature/employee/service/EmployeeService.java, backend/src/main/java/com/HelloRolha/HR/feature/refreshToken/controller/RefreshTokenController.java, backend/src/main/java/com/HelloRolha/HR/feature/refreshToken/model/RefreshToken.java, backend/src/main/java/com/HelloRolha/HR/feature/refreshToken/model/dto/TokenReq.java, backend/src/main/java/com/HelloRolha/HR/feature/refreshToken/model/dto/TokenRes.java, backend/src/main/java/com/HelloRolha/HR/feature/refreshToken/repo/RefreshTokenRepository.java, backend/src/main/java/com/HelloRolha/HR/feature/refreshToken/service/RefreshTokenService.java, backend/src/main/resources/application.yml
- redis 활용
- 현재 yml파일에 accessToken 기한을 테스트때문에 10초로 하였는데, 배포 시 변경필요
- 슬랙으로 redis서버 ova파일 첨부 (쿠버에도 있음)
Close: #319
=> [Feat] refreshToken 도입

frontend/src/pages/MainPage.vue
- 결재 현황 기능 추가 구현
- todo 리스트 기능 추가 구현
=> [Fix] 메인 페이지 수정

backend/src/main/java/com/HelloRolha/HR/config/utils/filter/JwtFilter.java, backend/src/main/java/com/HelloRolha/HR/error/ErrorCode.java, backend/src/main/java/com/HelloRolha/HR/feature/employee/model/entity/Employee.java, backend/src/main/java/com/HelloRolha/HR/feature/employee/service/EmployeeService.java, backend/src/main/java/com/HelloRolha/HR/feature/salary/scheduler/SalaryScheduler.java, backend/src/test/java/com/HelloRolha/HR/feature/employee/service/EmployeeServiceTest.java, backend/src/test/java/com/HelloRolha/HR/feature/position/service/PositionServiceTest.java
- CICD 기획서 작성을 위해 일부러 문제가 있는 코드를 올립니다.
=> [Test] 테스트 코드 비통과 및 젠킨스 빌드 실패를 위한 문법 오류

frontend/src/pages/MainPage.vue
=> [Fix] 메인 페이지 위치 수정

frontend/src/pages/BoardCreatePage.vue
=> [Fix] 페이지 버튼 변경

backend/src/main/java/com/HelloRolha/HR/feature/overtime/service/OvertimeService.java
- 데이터가 날아가서 모든 월의 월급을 계산하는 기능을 만듬
=> [Feat] 모든 월급 계산하는 기능

backend/src/main/java/com/HelloRolha/HR/feature/overtime/controller/OvertimeController.java, backend/src/main/java/com/HelloRolha/HR/feature/overtime/model/dto/OvertimeDto.java, backend/src/main/java/com/HelloRolha/HR/feature/overtime/service/OvertimeService.java
- read 메소드 fetchMapping 에서 getMapping으로 수정
- DTO에 작성자이름 추가
=> [Fix] Overtime 코드 수정

frontend/src/components/goout/GooutList.vue, frontend/src/components/goout/GooutRead.vue, frontend/src/pages/Approve/ApproveListPage.vue, frontend/src/pages/Approve/ApproveReadPage.vue, frontend/src/pages/BoardListPage.vue, frontend/src/pages/BoardReadPage.vue, frontend/src/pages/OvertimeDetailPage.vue, frontend/src/pages/OvertimeListPage.vue, frontend/tests/unit/approveCreatePage.spec.js, frontend/tests/unit/approveListPage.spec.js, frontend/tests/unit/departmentListModal.spec.js, frontend/tests/unit/gooutCreate.spec.js, frontend/tests/unit/gooutList.spec.js, frontend/tests/unit/login.spec.js, frontend/tests/unit/signup.spec.js
- List페이지 스타일 통일 및 Read페이지 스타일 통일
- Test코드 추가 및 변경
=> [Style] List & Read 페이지 스타일 변경
